modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/fishcute/Celestial/issues"
[[mods]]
modId="celestial"
version="${version}"
displayName="Celestial"
displayURL="https://github.com/fishcute/Celestial"
logoFile="icon.png"
authors="fishcute, block36_"
[[mixins]]
config="celestial.mixins.json"
description='''
A Minecraft mod for Fabric and Forge that allows you to customize the sky.
'''

[[dependencies.celestial]]
   modId="neoforge"
   mandatory=true
   versionRange="[21.1.219]"
   ordering="NONE"
   side="BOTH"
[[dependencies.celestial]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21.1]"
   ordering="NONE"
   side="BOTH"